apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - statefulset.yaml
  - service.yaml
  # ingressroute-tcp.yaml - moved to overlays

labels:
  - pairs:
      tier: database