apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin
    component: database-management
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@amoona.local
  PGADMIN_DEFAULT_PASSWORD: changeme-in-overlay
