apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  labels:
    app: harbor
type: Opaque
stringData:
  # Ces valeurs seront remplac√©es par le script generate-secrets.sh
  HARBOR_ADMIN_PASSWORD: "Harbor12345"
  HARBOR_DB_PASSWORD: "harbor_db_password"
  CORE_KEY: "core_key_change_me_32_chars_long"
  SECRET_KEY: "secret_key_change_me_16_chars"
  REGISTRY_HTTP_SECRET: "registry_http_secret_change_me"
