apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amoona-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: secrets-patch.yaml
  - path: resource-patches.yaml
  - path: ingress-patch.yaml

labels:
  - pairs:
      environment: prod

commonAnnotations:
  managed-by: kustomize
  environment: production
