apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-tcp
  annotations:
    description: "PostgreSQL TCP access for prod environment"
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`postgres.amoona.tech`) || HostSNI(`*`)
      services:
        - name: postgres
          port: 5432
  tls:
    passthrough: true
