apiVersion: v1
kind: Secret
metadata:
  name: {{SERVICE_NAME}}-secret
  labels:
    app: {{SERVICE_NAME}}
    tier: database
type: Opaque
stringData:
  POSTGRES_USER: "{{DB_USER}}"
  POSTGRES_PASSWORD: "{{DB_PASSWORD}}"
  POSTGRES_DB: "{{DB_NAME}}"
