apiVersion: v1
kind: ConfigMap
metadata:
  name: amoona-api-config
  labels:
    app: amoona-api
    app.kubernetes.io/name: amoona-api
    app.kubernetes.io/component: backend
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
