apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: amoona-api-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: amoona
  app.kubernetes.io/managed-by: kustomize
