apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: amoona-front-prod

namespace: amoona-prod

resources:
  - ../../../../base/apps/amoona-front
  - ingress.yaml

patches:
  - path: replicas-patch.yaml

commonLabels:
  environment: prod

images:
  # GitLab Container Registry
  - name: registry.gitlab.com/hypnozsarl/amoona-front
    newTag: "latest"