apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sonarqube

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/part-of: amoona-devtools
