apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  labels:
    app: sonarqube
type: Opaque
stringData:
  SONAR_JDBC_URL: "jdbc:postgresql://postgres:5432/sonarqube"
  SONAR_JDBC_USERNAME: "sonarqube"
  SONAR_JDBC_PASSWORD: "CHANGE_ME_sonarqube_password"
