apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - configmap-datasources.yaml
  - configmap-dashboards.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  tier: monitoring