apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amoona-api
  labels:
    app: amoona-api
    app.kubernetes.io/name: amoona-api
    app.kubernetes.io/component: backend
    environment: dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.dev.amoona.tech
      secretName: amoona-api-dev-tls
  rules:
    - host: api.dev.amoona.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amoona-api
                port:
                  number: 80
