apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    app: minio
    component: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: minio-admin
  MINIO_ROOT_PASSWORD: changeme-in-overlay