apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - falco-config.yaml
  - falco-daemonset.yaml
  # k8s-audit-policy.yaml is not a K8s resource, it's for API server configuration

labels:
  - pairs:
      tier: security
