apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}-config
  labels:
    app: {{SERVICE_NAME}}
    tier: microservice
data:
  APP_NAME: "{{SERVICE_NAME}}"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "{{PORT}}"
