apiVersion: v1
kind: Secret
metadata:
  name: amoona-api-secrets
  labels:
    app: amoona-api
    app.kubernetes.io/name: amoona-api
    environment: prod
type: Opaque
stringData:
  # Database - Ces valeurs doivent être remplacées par les vraies valeurs
  DB_HOST: "postgres.amoona-prod.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "amoona_saas"
  DB_USER: "amoonaDBA"
  DB_PASSWORD: "CHANGE_ME"
  # Redis
  REDIS_HOST: "redis.amoona-prod.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "CHANGE_ME"
  # MinIO
  MINIO_ENDPOINT: "http://minio.amoona-prod.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
  # JWT
  JWT_SECRET: "CHANGE_ME_WITH_A_SECURE_256_BIT_KEY"
