apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amoona-dev

resources:
  - namespace.yaml
  - ../../base
  - ingressroutes.yaml

patches:
  - path: secrets-patch.yaml
  - path: resource-patches.yaml
  - path: postgres-ingressroute-patch.yaml
  - path: postgres-service-patch.yaml

labels:
  - pairs:
      environment: dev

commonAnnotations:
  managed-by: kustomize
  environment: development
  last-deployed: "2025-12-09T14:15:00Z"
