apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_PASSWORD: "dev-postgres-amoona-2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_PASSWORD: "dev-minio-amoona-2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "dev-grafana-amoona-2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
stringData:
  REDIS_PASSWORD: "dev-redis-amoona-2024"
